In [1]:
import yfinance as yf

In [2]:
gold_data = yf.download('GC=F', start='2000-01-01', end='2024-01-01')

[*********************100%***********************]  1 of 1 completed

In [3]:
gold_data.head()

                  Open        High         Low       Close   Adj Close  Volume
Date
2000-08-30  273.899994  273.899994  273.899994  273.899994  273.899994       0
2000-08-31  274.799988  278.299988  274.799988  278.299988  278.299988       0
2000-09-01  277.000000  277.000000  277.000000  277.000000  277.000000       0
2000-09-05  275.799988  275.799988  275.799988  275.799988  275.799988       2
2000-09-06  274.200012  274.200012  274.200012  274.200012  274.200012       0

In [4]:
gold_data.info()

<class 'pandas.core.frame.DataFrame'>
DatetimeIndex: 5854 entries, 2000-08-30 to 2023-12-29
Data columns (total 6 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   Open       5854 non-null   float64
 1   High       5854 non-null   float64
 2   Low        5854 non-null   float64
 3   Close      5854 non-null   float64
 4   Adj Close  5854 non-null   float64
 5   Volume     5854 non-null   int64
dtypes: float64(5), int64(1)
memory usage: 320.1 KB

In [5]:
#gold_data[gold_data["Date"]=="2000-09-07"]

In [6]:
import requests
import pandas as pd

In [7]:
df=pd.read_csv("gold-dataset-sinha-khandait.csv")
df.head()

,Dates,URL,News,Price Direction Up,Price Direction Constant,Price Direction Down,Asset Comparision,Past Information,Future Information,Price Sentiment
0,28-01-2016,http://www.marketwatch.com/story/april-gold-do...,"april gold down 20 cents to settle at $1,116.1...",0,0,1,0,1,0,negative
1,13-09-2017,http://www.marketwatch.com/story/gold-prices-s...,gold suffers third straight daily decline,0,0,1,0,1,0,negative
2,26-07-2016,http://www.marketwatch.com/story/gold-futures-...,Gold futures edge up after two-session decline,1,0,0,0,1,0,positive
3,28-02-2018,https://www.metalsdaily.com/link/277199/dent-r...,dent research : is gold's day in the sun comin...,0,0,0,0,0,1,none
4,06-09-2017,http://www.marketwatch.com/story/gold-steadies...,"Gold snaps three-day rally as Trump, lawmakers...",0,0,1,0,1,0,negative

In [8]:
df.drop(columns="URL",inplace=True)
df.head()

,Dates,News,Price Direction Up,Price Direction Constant,Price Direction Down,Asset Comparision,Past Information,Future Information,Price Sentiment
0,28-01-2016,"april gold down 20 cents to settle at $1,116.1...",0,0,1,0,1,0,negative
1,13-09-2017,gold suffers third straight daily decline,0,0,1,0,1,0,negative
2,26-07-2016,Gold futures edge up after two-session decline,1,0,0,0,1,0,positive
3,28-02-2018,dent research : is gold's day in the sun comin...,0,0,0,0,0,1,none
4,06-09-2017,"Gold snaps three-day rally as Trump, lawmakers...",0,0,1,0,1,0,negative

In [9]:
df.rename(columns={'Dates': 'Date'}, inplace=True)
df.head()

,Date,News,Price Direction Up,Price Direction Constant,Price Direction Down,Asset Comparision,Past Information,Future Information,Price Sentiment
0,28-01-2016,"april gold down 20 cents to settle at $1,116.1...",0,0,1,0,1,0,negative
1,13-09-2017,gold suffers third straight daily decline,0,0,1,0,1,0,negative
2,26-07-2016,Gold futures edge up after two-session decline,1,0,0,0,1,0,positive
3,28-02-2018,dent research : is gold's day in the sun comin...,0,0,0,0,0,1,none
4,06-09-2017,"Gold snaps three-day rally as Trump, lawmakers...",0,0,1,0,1,0,negative

In [10]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10570 entries, 0 to 10569
Data columns (total 9 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   Date                      10570 non-null  object
 1   News                      10570 non-null  object
 2   Price Direction Up        10570 non-null  int64
 3   Price Direction Constant  10570 non-null  int64
 4   Price Direction Down      10570 non-null  int64
 5   Asset Comparision         10570 non-null  int64
 6   Past Information          10570 non-null  int64
 7   Future Information        10570 non-null  int64
 8   Price Sentiment           10570 non-null  object
dtypes: int64(6), object(3)
memory usage: 743.3+ KB

In [11]:
#df['Date'] = pd.to_datetime(df['Date']).dt.date
problematic_dates = df[~df['Date'].str.match(r'^\d{2}-\d{2}-\d{4}$')]

In [12]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10570 entries, 0 to 10569
Data columns (total 9 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   Date                      10570 non-null  object
 1   News                      10570 non-null  object
 2   Price Direction Up        10570 non-null  int64
 3   Price Direction Constant  10570 non-null  int64
 4   Price Direction Down      10570 non-null  int64
 5   Asset Comparision         10570 non-null  int64
 6   Past Information          10570 non-null  int64
 7   Future Information        10570 non-null  int64
 8   Price Sentiment           10570 non-null  object
dtypes: int64(6), object(3)
memory usage: 743.3+ KB

In [13]:
df[df["Date"]=="2000-09-07"]

Empty DataFrame
Columns: [Date, News, Price Direction Up, Price Direction Constant, Price Direction Down, Asset Comparision, Past Information, Future Information, Price Sentiment]
Index: []

In [14]:
df['Date'] = pd.to_datetime(df['Date'], format='%d-%m-%Y', errors='coerce')

In [15]:
df.head()

,Date,News,Price Direction Up,Price Direction Constant,Price Direction Down,Asset Comparision,Past Information,Future Information,Price Sentiment
0,2016-01-28,"april gold down 20 cents to settle at $1,116.1...",0,0,1,0,1,0,negative
1,2017-09-13,gold suffers third straight daily decline,0,0,1,0,1,0,negative
2,2016-07-26,Gold futures edge up after two-session decline,1,0,0,0,1,0,positive
3,2018-02-28,dent research : is gold's day in the sun comin...,0,0,0,0,0,1,none
4,2017-09-06,"Gold snaps three-day rally as Trump, lawmakers...",0,0,1,0,1,0,negative

In [16]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10570 entries, 0 to 10569
Data columns (total 9 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   Date                      10405 non-null  datetime64[ns]
 1   News                      10570 non-null  object
 2   Price Direction Up        10570 non-null  int64
 3   Price Direction Constant  10570 non-null  int64
 4   Price Direction Down      10570 non-null  int64
 5   Asset Comparision         10570 non-null  int64
 6   Past Information          10570 non-null  int64
 7   Future Information        10570 non-null  int64
 8   Price Sentiment           10570 non-null  object
dtypes: datetime64[ns](1), int64(6), object(2)
memory usage: 743.3+ KB

In [17]:
gold_data['Date'] = pd.to_datetime(df['Date']).dt.date

In [18]:
gold_data_reset = gold_data.reset_index(drop=True)

In [19]:
gold_data.rename(columns={'Date': 'Date_Original'}, inplace=True)
gold_data_reset = gold_data.reset_index()

In [20]:
df['Date'] = pd.to_datetime(df['Date'])
gold_data_reset['Date'] = pd.to_datetime(gold_data_reset['Date'])

In [21]:
total = pd.merge(gold_data_reset, df, on='Date', how='inner')

In [22]:
total.head()

,Date,Open,High,Low,Close,Adj Close,Volume,Date_Original,News,Price Direction Up,Price Direction Constant,Price Direction Down,Asset Comparision,Past Information,Future Information,Price Sentiment
0,2000-09-07,274.000000,274.000000,274.000000,274.000000,274.000000,125,NaN,palladium rallies as gold falls,0,0,1,1,1,0,negative
1,2000-09-08,273.299988,273.299988,273.299988,273.299988,273.299988,0,NaN,gold lower in quiet trading,0,0,1,0,1,0,negative
2,2000-09-14,272.399994,272.399994,272.399994,272.399994,272.399994,0,NaN,gold steady on dollar's strength,0,1,0,1,1,0,neutral
3,2000-10-10,272.399994,272.399994,272.399994,272.399994,272.399994,13,NaN,gold gains on dollar weakness,1,0,0,1,1,0,positive
4,2000-10-16,271.500000,271.500000,271.500000,271.500000,271.500000,5,NaN,gold slips for a second-straight day,0,0,1,0,1,0,negative

In [23]:
total.drop(columns="Date_Original",inplace=True)
total.head()

,Date,Open,High,Low,Close,Adj Close,Volume,News,Price Direction Up,Price Direction Constant,Price Direction Down,Asset Comparision,Past Information,Future Information,Price Sentiment
0,2000-09-07,274.000000,274.000000,274.000000,274.000000,274.000000,125,palladium rallies as gold falls,0,0,1,1,1,0,negative
1,2000-09-08,273.299988,273.299988,273.299988,273.299988,273.299988,0,gold lower in quiet trading,0,0,1,0,1,0,negative
2,2000-09-14,272.399994,272.399994,272.399994,272.399994,272.399994,0,gold steady on dollar's strength,0,1,0,1,1,0,neutral
3,2000-10-10,272.399994,272.399994,272.399994,272.399994,272.399994,13,gold gains on dollar weakness,1,0,0,1,1,0,positive
4,2000-10-16,271.500000,271.500000,271.500000,271.500000,271.500000,5,gold slips for a second-straight day,0,0,1,0,1,0,negative

In [24]:
total.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9846 entries, 0 to 9845
Data columns (total 15 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   Date                      9846 non-null   datetime64[ns]
 1   Open                      9846 non-null   float64
 2   High                      9846 non-null   float64
 3   Low                       9846 non-null   float64
 4   Close                     9846 non-null   float64
 5   Adj Close                 9846 non-null   float64
 6   Volume                    9846 non-null   int64
 7   News                      9846 non-null   object
 8   Price Direction Up        9846 non-null   int64
 9   Price Direction Constant  9846 non-null   int64
 10  Price Direction Down      9846 non-null   int64
 11  Asset Comparision         9846 non-null   int64
 12  Past Information          9846 non-null   int64
 13  Future Information        9846 non-null   int64
 14  Price Sentiment           9846 non-null   object
dtypes: datetime64[ns](1), float64(5), int64(7), object(2)
memory usage: 1.1+ MB

In [25]:
total[total["Date"]=="2000-09-07"]

,Date,Open,High,Low,Close,Adj Close,Volume,News,Price Direction Up,Price Direction Constant,Price Direction Down,Asset Comparision,Past Information,Future Information,Price Sentiment
0,2000-09-07,274.0,274.0,274.0,274.0,274.0,125,palladium rallies as gold falls,0,0,1,1,1,0,negative

In [26]:
total.columns

Index(['Date', 'Open', 'High', 'Low', 'Close', 'Adj Close', 'Volume', 'News',
       'Price Direction Up', 'Price Direction Constant',
       'Price Direction Down', 'Asset Comparision', 'Past Information',
       'Future Information', 'Price Sentiment'],
      dtype='object')

In [27]:
gold_data_reset[gold_data_reset["Date"]=="2000-09-07"]

        Date   Open   High    Low  Close  Adj Close  Volume Date_Original
5 2000-09-07  274.0  274.0  274.0  274.0      274.0     125           NaN

In [28]:
total.to_csv('D:/Task depi/prj data set/total_gold data.csv', index=False)

In [29]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score

In [30]:
total = total.sort_values('Date')

In [31]:
total['Date'] = pd.to_datetime(total['Date'])

In [32]:
features = total[['Open', 'High', 'Low', 'Volume', 'Price Direction Up', 
                   'Price Direction Constant', 'Price Direction Down']]
target = total['Close'].shift(-1)  # Predict the next day's closing price

# Drop the last row as it will have NaN in target due to shifting
features = features[:-1]
target = target[:-1]

# Splitting the data into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(features, target, test_size=0.2, random_state=42)

In [33]:
from sklearn.ensemble import RandomForestRegressor
model = RandomForestRegressor(n_estimators=100, random_state=42)
model.fit(X_train, y_train)

RandomForestRegressor(random_state=42)

In [34]:
predictions = model.predict(X_test)

# Evaluating the model
mse = mean_squared_error(y_test, predictions)
mae = mean_absolute_error(y_test, predictions)
r2 = r2_score(y_test, predictions)

print(f'Mean Squared Error: {mse}')
print(f'Mean Absolute Error: {mae}')
print(f'R-squared: {r2}')

# Display predictions
predictions_df = pd.DataFrame({'Actual': y_test, 'Predicted': predictions})
print(predictions_df)

Mean Squared Error: 93.5369028006134
Mean Absolute Error: 5.253644367338565
R-squared: 0.9992325946571123
           Actual    Predicted
9638  1236.000000  1235.994000
9647  1229.800049  1230.900024
106    316.500000   314.570997
1446   732.700012   732.985827
1513   879.500000   878.375540
...           ...          ...
1745   733.299988   804.869743
7704  1276.900024  1276.924022
1451   737.799988   732.326494
101    316.600006   320.888001
319    417.200012   421.294001

[1969 rows x 2 columns]

In [35]:
def get_price_direction(row):
    if row['Price Direction Up'] == 1:
        return 'Up'
    elif row['Price Direction Constant'] == 1:
        return 'Constant'
    elif row['Price Direction Down'] == 1:
        return 'Down'
    else:
        return 'Unknown'

total['Price Direction'] = total.apply(get_price_direction, axis=1)

In [36]:
total.head()

,Date,Open,High,Low,Close,Adj Close,Volume,News,Price Direction Up,Price Direction Constant,Price Direction Down,Asset Comparision,Past Information,Future Information,Price Sentiment,Price Direction
0,2000-09-07,274.000000,274.000000,274.000000,274.000000,274.000000,125,palladium rallies as gold falls,0,0,1,1,1,0,negative,Down
1,2000-09-08,273.299988,273.299988,273.299988,273.299988,273.299988,0,gold lower in quiet trading,0,0,1,0,1,0,negative,Down
2,2000-09-14,272.399994,272.399994,272.399994,272.399994,272.399994,0,gold steady on dollar's strength,0,1,0,1,1,0,neutral,Constant
3,2000-10-10,272.399994,272.399994,272.399994,272.399994,272.399994,13,gold gains on dollar weakness,1,0,0,1,1,0,positive,Up
4,2000-10-16,271.500000,271.500000,271.500000,271.500000,271.500000,5,gold slips for a second-straight day,0,0,1,0,1,0,negative,Down

In [37]:
total.drop(columns=['Price Direction Up', 'Price Direction Constant',
       'Price Direction Down'],inplace=True)
total.head()

,Date,Open,High,Low,Close,Adj Close,Volume,News,Asset Comparision,Past Information,Future Information,Price Sentiment,Price Direction
0,2000-09-07,274.000000,274.000000,274.000000,274.000000,274.000000,125,palladium rallies as gold falls,1,1,0,negative,Down
1,2000-09-08,273.299988,273.299988,273.299988,273.299988,273.299988,0,gold lower in quiet trading,0,1,0,negative,Down
2,2000-09-14,272.399994,272.399994,272.399994,272.399994,272.399994,0,gold steady on dollar's strength,1,1,0,neutral,Constant
3,2000-10-10,272.399994,272.399994,272.399994,272.399994,272.399994,13,gold gains on dollar weakness,1,1,0,positive,Up
4,2000-10-16,271.500000,271.500000,271.500000,271.500000,271.500000,5,gold slips for a second-straight day,0,1,0,negative,Down

In [38]:
total.to_csv('D:/Task depi/prj data set/total_gold data1.csv', index=False)

In [39]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import classification_report, accuracy_score
from sklearn.preprocessing import LabelEncoder

In [40]:
label_encoder = LabelEncoder()
total['Price Direction'] = label_encoder.fit_transform(total['Price Direction'])
total['Price Sentiment'] = label_encoder.fit_transform(total['Price Sentiment'])
# تحديد الميزات والهدف
X = total[['Open', 'High', 'Close', 'Volume', 'Asset Comparision', 'Past Information', 'Future Information','Price Sentiment']]  
y = total['Price Direction']

In [41]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [42]:
model = RandomForestClassifier(n_estimators=100, random_state=42)
model.fit(X_train, y_train)

RandomForestClassifier(random_state=42)

In [43]:
y_pred = model.predict(X_test)

In [45]:
accuracy = accuracy_score(y_test, y_pred)
classification_rep = classification_report(y_test, y_pred)

print(f"Accuracy: {accuracy*100}%")
print("Classification Report:")
print(classification_rep)

Accuracy: 99.39086294416244%
Classification Report:
              precision    recall  f1-score   support

           0       0.96      0.89      0.92        79
           1       0.99      1.00      0.99       733
           2       1.00      0.99      1.00       333
           3       1.00      1.00      1.00       825

    accuracy                           0.99      1970
   macro avg       0.99      0.97      0.98      1970
weighted avg       0.99      0.99      0.99      1970